### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by ximeng96** [Simple-Robotics/proxsuite#205]
I am not able to install the package on my computer (intel7, windows 10). I have tried the both ways.
Pip:
ERROR: Could not find a version that satisfies the requirement proxsuit (from versions: none)
ERROR: No matching distribution found for proxsuit

Conda:
(base) C:\Users\Administrator>conda install proxsuite -c conda-forge
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\gateways\repodata\__init__.py", line 132, in conda_http_errors
        yield
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\gateways\repodata\__init__.py", line 101, in repodata
        response.raise_for_status()
      File "C:\Users\Administrator\anaconda3\lib\site-packages\requests\models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/gurobi/win-64/current_repodata.json

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Administrator\anaconda3\lib\site-packages\requests\models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\simplejson\__init__.py", line 525, in loads
        return _default_decoder.decode(s)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\simplejson\decoder.py", line 372, in decode
        obj, end = self.raw_decode(s)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\simplejson\decoder.py", line 402, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\cli\main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 91, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\notices\core.py", line 109, in wrapper
        return func(*args, **kwargs)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\cli\install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\solve.py", line 132, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\solve.py", line 175, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\solve.py", line 280, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\common\io.py", line 84, in decorated
        return f(*args, **kwds)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\solve.py", line 447, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\solve.py", line 1060, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 124, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "C:\Users\Administrator\anaconda3\lib\concurrent\futures\_base.py", line 609, in result_iterator
        yield fs.pop().result()
      File "C:\Users\Administrator\anaconda3\lib\concurrent\futures\_base.py", line 439, in result
        return self.__get_result()
      File "C:\Users\Administrator\anaconda3\lib\concurrent\futures\_base.py", line 391, in __get_result
        raise self._exception
      File "C:\Users\Administrator\anaconda3\lib\concurrent\futures\thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 113, in <lambda>
        subdir_query = lambda url: tuple(
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 129, in query
        self.load()
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 215, in load
        _internal_state = self._load()
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 323, in _load
        raw_repodata_str = self._repo.repodata(mod_etag_headers)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\gateways\repodata\__init__.py", line 101, in repodata
        response.raise_for_status()
      File "C:\Users\Administrator\anaconda3\lib\contextlib.py", line 137, in __exit__
        self.gen.throw(typ, value, traceback)
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\gateways\repodata\__init__.py", line 179, in conda_http_errors
        raise RepodataIsEmpty(
      File "C:\Users\Administrator\anaconda3\lib\site-packages\conda\exceptions.py", line 461, in __init__
        body = response.json()
      File "C:\Users\Administrator\anaconda3\lib\site-packages\requests\models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ C:\Users\Administrator\anaconda3\Scripts\conda-script.py install proxsuite -c conda-forge`

  environment variables:
                 CIO_TEST=<not set>
        CMAKE_PREFIX_PATH=C:\Users\Administrator\anaconda3\envs\formkl\Library\bin
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\Administrator\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\Administrator\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\Administrator\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\Administrator\anaconda3\python.exe
               CONDA_ROOT=C:\Users\Administrator\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
             GIT_LFS_PATH=C:\Program Files\Git LFS
                 HOMEPATH=\Users\Administrator
               LD_PRELOAD=<not set>
                     PATH=C:\Users\Administrator\anaconda3;C:\Users\Administrator\anaconda3\Libr
                          ary\mingw-w64\bin;C:\Users\Administrator\anaconda3\Library\usr\bin;C:\
                          Users\Administrator\anaconda3\Library\bin;C:\Users\Administrator\anaco
                          nda3\Scripts;C:\Users\Administrator\anaconda3\bin;C:\Users\Administrat
                          or\anaconda3\condabin;C:\Users\Administrator\win64\bin;C:\Program
                          Files (x86)\Intel\oneAPI\tbb\latest\redist\intel64\vc_mt;C:\Program
                          Files (x86)\Intel\oneAPI\tbb\latest\redist\ia32\vc_mt;C:\Program Files
                          (x86)\Intel\oneAPI\compiler\latest\windows\redist\intel64_win\compiler
                          ;C:\Program Files (x86)\Intel\oneAPI\compiler\latest\windows\redist\ia
                          32_win\compiler;C:\Program
                          Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\Program
                          Files\MiKTeX\miktex\bin\x64;C:\Program Files\Git LFS;C:\Program
                          Files\MATLAB\R2022b\bin;C:\Program Files\MATLAB\R2022a\bin;C:\Program
                          Files\CMake\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Intel\
                          oneAPI\mkl\bin;C:\Users\Administrator\AppData\Local\Programs\Python\Py
                          thon36\Scripts;C:\Users\Administrator\AppData\Local\Programs\Python\Py
                          thon36;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\U
                          sers\Administrator\AppData\Local\GitHubDesktop\bin;C:\Windows\system32
                          ;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerS
                          hell\v1.0
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\Administrator\anaconda3
            shell level : 1
       user config file : C:\Users\Administrator\.condarc
 populated config files : C:\Users\Administrator\.condarc
          conda version : 23.1.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\Administrator\anaconda3  (writable)
      conda av data dir : C:\Users\Administrator\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/gurobi/win-64
                          https://conda.anaconda.org/gurobi/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Administrator\anaconda3\pkgs
                          C:\Users\Administrator\.conda\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Administrator\anaconda3\envs
                          C:\Users\Administrator\.conda\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.9.13 Windows/10 Windows/10.0.18363
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:

Do you have any ideas why this happen? Thank you.

**Comment by jcarpent** [comment]
You should work with a clean environment with conda. You should not work in the base environment.

**Comment by ximeng96** [comment]
I solved this problem and now I am able to install the package. Thanks.
